apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: young-hummingbird-python-development
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/young-hummingbird-python/overlays/development
    repoURL: https://github.com/rhtap-hub/young-hummingbird-python-gitops.git
    targetRevision: main
  destination:
    namespace: flavius-e2e-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
