apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: young-hummingbird-python 
  janus-idp.io/tekton: young-hummingbird-python
  backstage.io/kubernetes-id: young-hummingbird-python
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: young-hummingbird-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  