apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: young-hummingbird-python-gitops-repository
spec:
  url: https://github.com/rhtap-hub/young-hummingbird-python-gitops